name: hospital_mang2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Network
  dio: ^5.4.2+1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Provider
  provider: ^6.1.2

  # Storage
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Flutter generation
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.9

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
      - assets/images/

flutter_intl:
  enabled: true